### ISSUE TITLE
Allow embedding all images

### ISSUE THREAD

**Issue by LaurenzV** [linebender/kompari#8]
From what I can tell, the left/right images will always be embedded as paths, while the diff image will be embedded as a base64-encoded PNG. It would be useful if there were a CLI flag that allows embedding everything as base64 encoded images (including the left/right images), so that you can have a single, dependency-free HTML report without having to send the folders containing the images in addition.

**Comment by spirali** [comment]
I like the idea, I will look at it tomorrow.
